# Generated by Django 5.2.5 on 2025-08-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["id"]},
        ),
    ]
